### ISSUE TITLE
Worker fails to find ENV var and crashes

### ISSUE THREAD

**Issue by whoabuddy** [magicstx/supplier-server#6]
I can reproduce this issue in 2203a53 both locally and using the Render deployment. Both versions of the worker are crashing with:

`Error: Missing required ENV variable: SUPPLIER_NETWORK`

Local example:

```
/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/src/config.ts:33
    if (!value) throw new Error(`Missing required ENV variable: ${key}`);
                ^

Error: Missing required ENV variable: SUPPLIER_NETWORK
    at getEnv (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/src/config.ts:12:21)
    at Object.getNetworkKey (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/src/config.ts:72:10)
    at redisKeyPrefix (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/src/store.ts:2:41)
    at Object.createRedisClient (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/src/store.ts:33:21)
    at Object.initWorkerThread (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/src/worker/index.ts:10:92)
    at Object.<anonymous> (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/scripts/worker.ts:1:49)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .ts] (/home/whoabuddy/Dev/bitcoin/magicstx/supplier-server/node_modules/pirates/lib/index.js:141:7)
error Command failed with exit code 1.
```

Render example:

![image](https://user-images.githubusercontent.com/9038904/180891446-1caa97c8-b416-4a78-93db-0027794dfebb.png)

The value is definitely set in the config and worked with `yarn register-supplier` [without issue](https://explorer.stacks.co/txid/0x58553e7ecc68c8d6e2a74840c5abeab83c1d5e6cd526760ba6266eea1dea17e1?chain=testnet).

Here is the output of `yarn check-config`:

```
Server config:
    btcAddress: "mnSTuSa13UzgrVLkBhutU1u7s36ez4sRFw"
    stxAddress: "ST1BHYY1HNHM9MZXSTW9NVGNPGBF5S108D6H1CEP"
    btcNetwork: "testnet"
    operatorId: 3
    electrumConfig: {
      "host": "blackie.c3-soft.com",
      "port": 57006,
      "protocol": "ssl"
    }
    topic: "start"

Configured contracts:
    bridge: "ST2ZTY9KK9H0FA0NVN3K8BGVN6R7GYVFG6BE7TAR1.bridge"
    xbtc: "ST2ZTY9KK9H0FA0NVN3K8BGVN6R7GYVFG6BE7TAR1.Wrapped-Bitcoin"
    network: "testnet"
    btc: 1.25321
    stx: 49999
```

**Comment by whoabuddy** [comment]
This looks to be an issue with the `.env` file not loading - not sure why but was able to workaround by using the [dotenv package](https://www.npmjs.com/package/dotenv).

Steps to fix below:

`yarn add dotenv --save`

Then in `src/config.ts` add `import 'dotenv/config';` at the top.

Looking at the git diff I think dotenv was already installed, and oddly enough the process worked fine at the registration step. I can submit a PR if it makes sense.

**Comment by whoabuddy** [comment]
Noting that I also found a reference to `dotenv` in the package.json:

https://github.com/magicstx/supplier-server/blob/2203a534b24ca5fcd7bd7d23fc51e121546c0d2f/package.json#L6-L7

Is the solution here just to add `-r dotenv/config` to the following entries?
- start
- server
- worker

**Comment by dumbledope** [comment]
Hey - I should document this better, but I'm trying to be intentional about not using .env in production. It probably varies, but in general, cloud hosts do a better job of securing environment variables compared to just files on disk. Are you adding the .env to git to support it ending up in Render? Even with a private repo, I would probably recommend against it.

If you wanted to use .env in production, you could also just run `yarn dev` / `yarn server:dev` with `NODE_ENV=production` in your .env. I think .env variables take precedence?

**Comment by whoabuddy** [comment]
> I should document this better, but I'm trying to be intentional about not using .env in production. It probably varies, but in general, cloud hosts do a better job of securing environment variables compared to just files on disk.

I agree with you here, this issue and related PR is around how the environment variables are loaded, based on my experience building locally and using the Deploy to Render button.

Locally I was using a `.env` file based on the [Host a Supplier](https://magicstx.gitbook.io/magic-protocol/guides/host-a-supplier) instructions, but when I went to run `yarn worker` and `yarn server` the worker would fail with the error outlined above.

Following that I tried the Deploy to Render button, input the requested environment variables on setup, and deployed the blueprint. The worker service failed repeatedly with the same error until I suspended it.

When I changed my local code to run `-r dotenv/config` with the node commands in both `yarn worker` and `yarn start`, the worker started successfully and everything ran without issue. I was then able to perform a few swaps, and thought that same change could fix the render deployment (assuming it was also using the same `yarn` commands).

One other thing I noticed with the render worker, there is no environment variable for `SUPPLIER_NETWORK`:

![Screenshot from 2022-07-28 15-21-28](https://user-images.githubusercontent.com/9038904/181648801-0d37891e-5c69-458e-9dcf-4f9422f60ace.png)
